### ISSUE TITLE
Please extend device-plugin-operator template to specify container resources (requests & limits) 

### ISSUE THREAD

**Issue by MustDie95** [intel/helm-charts#34]
inteldeviceplugin-controller container is periodically OOM-killed due to exceeding the memory limits:

![intel-device-plugins-operator-oom](https://user-images.githubusercontent.com/22371448/236416053-2225aac3-de7b-4120-b8b3-fa53d1576aed.jpg)

This time it was in the same time with launching of the enclave with a 20GB EPC. I don't know if these events are related. We have enclaves with 256GB but usually there were no such OOMKills.

Typical memory usage looks like this:

![intel-device-plugins-operator-7day](https://user-images.githubusercontent.com/22371448/236416035-5929d442-5a43-48c8-badb-0cc0e8271760.jpg)

Now container resources are hardcoded as:

```
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 20Mi
```

Please extend device-plugin-operator template to specify container resources (requests & limits) in values.
