### ISSUE TITLE
Please extend the device-plugins-operator chart with node selectors (exec format error)

### ISSUE THREAD

**Issue by samip5** [intel/helm-charts#39]
Currently the deployment will fail if it happens to be scheduled onto an arm64 node, and I seem to have no way to influence it eg via tolerations.

The following Helm-Release:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.27.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
```

Results in the operator deployment failing with exec format error on non-amd64 node.
