### ISSUE TITLE
Issue upgrading helm chart `intel-device-plugins-gpu` from `v0.27.1` to `v0.28.0`

### ISSUE THREAD

**Issue by onedr0p** [intel/helm-charts#41]
### helm values

```yaml
name: intel-device-plugin-gpu
sharedDevNum: 3
nodeFeatureRule: true
```

### error

```
Invalid: NodeFeatureRule.nfd.k8s-sigs.io "intel-gpu-platform-labeling" is invalid: [spec.rules[1].labels: Invalid value: "null": spec.rules[1].labels in body must be of type object: "null", spec.rules[2].labels: Invalid value: "null": spec.rules[2].labels in body must be of type object: "null", spec.rules[3].labels: Invalid value: "null": spec.rules[3].labels in body must be of type object: "null"]
```
